repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: check-builtin-literals
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: requirements-txt-fixer
    - id: check-yaml
    - id: check-toml

  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort

  - repo: https://github.com/myint/docformatter
    rev: v1.5.1
    hooks:
    - id: docformatter
      args: [--in-place, --wrap-summaries=88, --wrap-descriptions=88, --blank]
      files: ".*.py$"

  - repo: local
    hooks:
    - id: flake8
      name: flake8
      language: python
      entry: pflake8
      files: ".*.py$"

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    - id: pydocstyle
      args: [--convention=numpy]
      additional_dependencies: [toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
    - id: mypy
      entry: python3 -m mypy --config-file pyproject.toml
      language: system
      types: [python]
<<<<<<< HEAD
      exclude: "apps|use_cases|tests|cyclops/(process|models|evaluate|workflow)"
=======
      exclude: "apps|use_cases|tests|cyclops/(process|models|monitor|workflow)"
>>>>>>> origin/main

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      language: python
      entry: pylint
      files: ".*.py$"
      exclude: fsd

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest -m "not integration_test"
      language: system
      pass_filenames: false
      always_run: true

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.3
    hooks:
    - id: nbqa-black
    - id: nbqa-isort
    - id: nbqa-check-ast
    - id: nbqa-flake8
    # ignore E203/W503 to avoid conflict with black:
    # https://github.com/psf/black/issues/354
      args: ['--ignore=E203,W503']
    # - id: nbqa-mypy

  - repo: local
    hooks:
    - id: nbstripout
      name: nbstripout
      language: python
      entry: nbstripout
      exclude: ^docs/source/tutorials/.*/.*\.ipynb$
