model_params:
  alpha: 1.e-1
  hidden_layer_sizes: [256, 256, 256, 256]
  early_stopping: False
  learning_rate: "adaptive"
  batch_size: 64
best_model_params:
  alpha: [1.e-1, 1.e-2, 1.e-3, 1.e-4, 1.e-5, 1.e-6, 1.e-7]
  metric: 'roc_auc'
